version: '3'
services:
  forensic300:
    restart: always
    build: .
#        context: .
#        dockerfile: ./Dockerfile
    ports:
        - "9002:80"
    volumes:
        - ./app:/app
    command: gunicorn -w 4 -b :80 wsgi
